### ISSUE TITLE
Alternate English provider with refresh ability 

### ISSUE THREAD

**Issue by harphere** [Xposed-Modules-Repo/com.yubyf.quotelockx#1]
Hi, thanks for this cool project. Is there another English source that can be used since BrainyQuote does not allow to auto refresh?

**Comment by Yubyf** [comment]
Unfortunately, BrainyQuote is currently the only source in English found by our contributors, please suggest if you have a good idea.

Finally, it is best to submit issues and suggestions in the [original repository](https://github.com/Yubyf/QuoteLockX/issues)

**Comment by Yubyf** [comment]
@nickelnine I found another English quotes provider - [Lib Quotes](https://libquotes.com/). But its update interval is also one day. It will be added in the next version.

**Comment by harphere** [comment]
Awesome! Thanks so much.
