### ISSUE TITLE
Cannot import CSV

### ISSUE THREAD

**Issue by githubForAashish** [Xposed-Modules-Repo/com.yubyf.quotelockx#2]
First of Great work here!! Up the devs.
Now comming to the issue.... Im not able to import CSV files with quotes.... ive tried 2 /3 columns with/without headers ..but cant seem to get it work...could you also mention the format of CSV needed?

**Comment by Yubyf** [comment]
Sorry, you may have misunderstood. The import CSV feature is mainly set only for the export CSV feature. Its format is a bit unfriendly to manual generation. You can write your custom quotes througth the custom quote provider in settings.

Of course, you can also import your own CSV files that are not exported by the APP.
The columns are "AUTHOR", "MD5", "SOURCE", "TEXT", "_ID". These columns are from the structure of database file. The column "MD5" is calculated from content string of "TEXTSOURCEAUTHOR" and it is unique. The column "_ID" is the primary key just like "1","2","3"...

You can collect a quote and export it to CSV to see a specific example.

> Here is an example.
> "AUTHOR","MD5","SOURCE","TEXT","_ID"
> "Charles Kettering","cb59a0d696e4788f1901d192021225c8","","One fails forward toward success.","1"
